typeset -g POWERLEVEL9K_BACKGROUND=#534341 
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=#ffb4a8
typeset -g POWERLEVEL9K_TIME_FOREGROUND=#d8c2be
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=#dec48c
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=#dec48c
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=#dec48c
